development:
  face_match_threshold: 0.6  # Threshold for face matching confidence
  # Pinecone index names
  pinecone:
    face_embeddings_index_nm: "face-embeddings"
    region: "us-east-1"  # Pinecone region
    api_key: "pcsk_5r25T5_EELsdTCB9EwgdoXeDuVeDAA3A4ZJ5zHbtiTkZbGtwGKMP6DvQnJ7UhJKNynBPUR"
